version: "3.8"
services:
    db:
        image: postgres:15-alpine
        environment:
            POSTGRES_USER: user_teste
            POSTGRES_PASSWORD: password_teste
            POSTGRES_DB: db_transcricao
        ports:
            - "5432:5432"
